apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: open5gs
spec:
  selector:
    app: upf
  ports:
  - name: pfcp
    port: 8805
    targetPort: 8805
    protocol: UDP
  - name: gtpu
    port: 2152
    targetPort: 2152
    protocol: UDP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: upf
  namespace: open5gs
spec:
  serviceName: upf
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      initContainers:
      - name: wait-for-smf
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          until nc -z smf.open5gs.svc.cluster.local 7777; do
            echo "Waiting for SMF..."
            sleep 2
          done
      
      containers:
      - name: upf
        image: open5gs-upf:latest
        imagePullPolicy: Never

        securityContext:
          capabilities:
            add:
            - NET_ADMIN  # Required for GTP-U and iptables
            - NET_RAW
            - SYS_ADMIN
          privileged: true  # Required for TUN device and iptables
        
        ports:
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        - name: gtpu
          containerPort: 2152
          protocol: UDP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        
        env:
        - name: DB_URI
          value: "mongodb://admin:1423@mongodb.open5gs.svc.cluster.local:27017/open5gs?authSource=admin"
        
        volumeMounts:
        - name: config
          mountPath: /etc/open5gs/custom
        - name: logs
          mountPath: /var/log/open5gs
          subPath: upf
        - name: dev-net-tun 
          mountPath: /dev/net/tun
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
        
        livenessProbe:
          exec:
            command: ["pgrep", "open5gs-upfd"]
          initialDelaySeconds: 15
          periodSeconds: 10
        
        readinessProbe:
          exec:
            command: ["pgrep", "open5gs-upfd"]
          initialDelaySeconds: 10
          periodSeconds: 10
      
      volumes:
      - name: config
        configMap:
          name: upf-config
      - name: logs
        persistentVolumeClaim:
          claimName: open5gs-logs-pvc
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice