apiVersion: v1
kind: PersistentVolume
metadata:
  name: open5gs-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/open5gs-logs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-logs-pvc
  namespace: open5gs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi