# This manifest defines the Service and Deployment for the Open5GS UDM.
# - The Service provides the stable DNS name `open5gs-udm-svc`.
# - The Deployment ensures one replica of the `open5gs-udm` container is running.
# - It mounts the `open5gs-config` ConfigMap to load its `udm.yaml` file.

apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm-svc
  namespace: open5gs
  labels:
    app: open5gs-udm
spec:
  ports:
    - port: 7777
      targetPort: 7777
      name: sbi
  selector:
    app: open5gs-udm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-udm-deployment
  namespace: open5gs
  labels:
    app: open5gs-udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-udm
  template:
    metadata:
      labels:
        app: open5gs-udm
    spec:
      containers:
      - name: udm
        image: gradiantcharts/open5gs-udm
        ports:
        - containerPort: 7777
        command: ["open5gs-udmd"]
        args: ["-c", "/open5gs/config/udm.yaml"]
        volumeMounts:
        - name: open5gs-config-volume
          mountPath: /open5gs/config
      volumes:
      - name: open5gs-config-volume
        configMap:
          name: open5gs-config

