# This manifest defines the Service and Deployment for the Open5GS UDR.
# - The Service provides the stable DNS name `open5gs-udr-svc`.
# - The Deployment ensures one replica of the `open5gs-udr` container is running.
# - It mounts the `open5gs-config` ConfigMap to load its `udr.yaml` file,
#   which contains the connection string to the MongoDB service.

apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr-svc
  namespace: open5gs
  labels:
    app: open5gs-udr
spec:
  ports:
    - port: 7777
      targetPort: 7777
      name: sbi
  selector:
    app: open5gs-udr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-udr-deployment
  namespace: open5gs
  labels:
    app: open5gs-udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-udr
  template:
    metadata:
      labels:
        app: open5gs-udr
    spec:
      containers:
      - name: udr
        image: gradiantcharts/open5gs-udr
        ports:
        - containerPort: 7777
        command: ["open5gs-udrd"]
        args: ["-c", "/open5gs/config/udr.yaml"]
        volumeMounts:
        - name: open5gs-config-volume
          mountPath: /open5gs/config
      volumes:
      - name: open5gs-config-volume
        configMap:
          name: open5gs-config

