# This manifest defines the Service and Deployment for the Open5GS PCF.
# - The Service provides the stable DNS name `open5gs-pcf-svc`.
# - The Deployment ensures one replica of the `open5gs-pcf` container is running.
# - It mounts the `open5gs-config` ConfigMap to load its `pcf.yaml` file.

apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcf-svc
  namespace: open5gs
  labels:
    app: open5gs-pcf
spec:
  ports:
    - port: 7777
      targetPort: 7777
      name: sbi
  selector:
    app: open5gs-pcf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-pcf-deployment
  namespace: open5gs
  labels:
    app: open5gs-pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-pcf
  template:
    metadata:
      labels:
        app: open5gs-pcf
    spec:
      containers:
      - name: pcf
        image: gradiantcharts/open5gs-pcf
        ports:
        - containerPort: 7777
        command: ["open5gs-pcfd"]
        args: ["-c", "/open5gs/config/pcf.yaml"]
        volumeMounts:
        - name: open5gs-config-volume
          mountPath: /open5gs/config
      volumes:
      - name: open5gs-config-volume
        configMap:
          name: open5gs-config

