# --- What is this file? ---
# This is a special manifest for the AMF. It defines a Service of type
# `NodePort` to allow external gNodeB traffic into the cluster.

# --- Kubernetes Service for AMF (Type: NodePort) ---
# This Service is different from the others.
# `type: NodePort` tells Kubernetes to open a specific high-numbered port on
# every physical cluster node. Any traffic sent to `<Node_IP>:<NodePort>`
# will be forwarded to the AMF pod's internal NGAP port (38412).
# This is the gateway for your external gNodeB.
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-svc
  namespace: open5gs
  labels:
    app: open5gs-amf
spec:
  type: NodePort
  ports:
    # Port for internal SBI communication
    - port: 7777
      targetPort: 7777
      name: sbi
    # Port for external NGAP communication from gNodeB
    - port: 38412
      targetPort: 38412
      # The nodePort is the high-numbered port that will be opened on all K8s nodes.
      # If left commented, Kubernetes will assign a random one from 30000-32767.
      # nodePort: 30412
      protocol: SCTP # NGAP uses SCTP
      name: ngap
  selector:
    app: open5gs-amf
---
# --- Kubernetes Deployment for AMF ---
# This Deployment is standard. It runs the AMF container and mounts the
# configuration, just like the other NFs.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf-deployment
  namespace: open5gs
  labels:
    app: open5gs-amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-amf
  template:
    metadata:
      labels:
        app: open5gs-amf
    spec:
      containers:
      - name: amf
        image: gradiantcharts/open5gs-amf
        ports:
        - containerPort: 7777
        - containerPort: 38412
          protocol: SCTP
        command: ["open5gs-amfd"]
        args: ["-c", "/open5gs/config/amf.yaml"]
        volumeMounts:
        - name: open5gs-config-volume
          mountPath: /open5gs/config
      volumes:
      - name: open5gs-config-volume
        configMap:
          name: open5gs-config

