apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: open5gs
data:
  amf.yaml: |
    logger:
      level: info
      file: /var/log/open5gs/amf.log
    
    amf:
      # SBI - Internal communication via services
      sbi:
        server:
          - address: 0.0.0.0  # All interfaces
            port: 7777
        client:
          scp:
            - uri: http://scp.open5gs.svc.cluster.local:7777
      
      # NGAP - External communication with gNB
      # CRITICAL: Use your K3s node IP here
      ngap:
        server:
          - address: 192.168.50.200  # CHANGE THIS!
            port: 38412
      
        metrics:
          server:
            - address: 0.0.0.0
              port: 9090
        guami:
          - plmn_id:
              mcc: 001
              mnc: 01
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: 001
              mnc: 01
            tac: 1
        plmn_support:
          - plmn_id:
              mcc: 001
              mnc: 01
            s_nssai:
              - sst: 1
                dnn: embb.testbed
              - sst: 2
                dnn: urllc.v2x
              - sst: 3
                dnn: mmtc.testbed
        security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
          full: Digital Hugs Network
          short: DigitalHugs <3
        amf_name: open5gs-amf0
        time:
          t3512:
            value: 540