apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: open5gs
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log
        timestamp: true
      default:
        timestamp: false
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp.open5gs.svc.cluster.local:7777