apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-config
  namespace: open5gs
data:
  nssf.yaml: |
    logger:
      level: info
      file: 
        path: /var/log/open5gs/nssf.log
        timestamp: true
      default:
        timestamp: false
    #  level: info   # fatal|error|warn|info(default)|debug|
    
    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp.open5gs.svc.cluster.local:7777
          nsi:
            - uri: http://nrf.open5gs.svc.cluster.local:7777
              s_nssai:
                sst: 1
            - uri: http://nrf.open5gs.svc.cluster.local:7777
              s_nssai:
                sst: 2
            - uri: http://nrf.open5gs.svc.cluster.local:7777
              s_nssai:
                sst: 3