apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: open5gs
data:
  smf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/smf.log
        timestamp: true
      default:
        timestamp: true
      level: debug   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
           - uri: http://nrf.open5gs.svc.cluster.local:7777
          # scp:
          #   - uri: http://scp.open5gs.svc.cluster.local:7777
      pfcp:
        server:
          - address: 0.0.0.0
            port: 8805
        # client:
        #   upf:
        #     - address: upf.open5gs.svc.cluster.local
        #       dnn: ['embb.testbed', 'urllc.v2x', 'mmtc.testbed']
      # gtpc:
      #   server:
      #     - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      session:
        - subnet: 10.45.0.0/24
          dnn: embb.testbed
          gateway: 10.45.0.1
        - subnet: 10.45.1.0/24
          dnn: urllc.v2x
          gateway: 10.45.1.1
        - subnet: 10.45.2.0/24
          dnn: mmtc.testbed
          gateway: 10.45.2.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
    #  p-cscf:
    #    - 10.10.0.1
    #    - ::1
    #  ctf:
    #    enabled: auto   # auto(default)|yes|no
      # freeDiameter: /etc/freeDiameter/smf.conf
      info:
        - s_nssai:
            - sst: 1
              dnn:
                - embb.testbed
            - sst: 2
              dnn:
                - urllc.v2x
            - sst: 3
              dnn:
                - mmtc.testbed
          tai:
            - plmn_id:
                mcc: 001
                mnc: 01
              tac: 1