apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: open5gs
data:
  udm.yaml: |

    logger:
      file:
        path: /var/log/open5gs/udm.log
        timestamp: true
      default:
        timestamp: true
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    udm:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://nrf.open5gs.svc.cluster.local:7777
          # scp:
          #   - uri: http://scp.open5gs.svc.cluster.local:7777