apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      level: info
      file: 
        path: /var/log/open5gs/upf.log
        timestamp: true
      default:
        timestamp: false
    #  level: info   # fatal|error|warn|info(default)|debug|trace
    
    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    upf:
      # PFCP interface (N4)
      pfcp:
        server:
          - address: 192.168.50.200
        client:
          # smf:
          #   - address: 192.168.50.200
          #     port: 8806
      # GTP-U interface (N3)
      gtpu:
        server:
          - address: 192.168.50.200
      
      # DNN configurations
      session:
      # DNN: embb.testbed (eMBB - Enhanced Mobile Broadband)
      - subnet: 10.45.0.0/24
        gateway: 10.45.0.1
        dnn: embb.testbed
        dev: ogstun
      # DNN: urllc.v2x (URLLC - Ultra Reliable Low Latency Communications)
      - subnet: 10.45.1.0/24
        gateway: 10.45.1.1
        dnn: urllc.v2x
        dev: ogstun2
      # DNN: mmtc.testbed (mMTC - Massive Machine Type Communications)  
      - subnet: 10.45.2.0/24
        gateway: 10.45.2.1
        dnn: mmtc.testbed
        dev: ogstun3
      # IPv6 support
      - subnet: 2001:db8:cafe::/48
        gateway: 2001:db8:cafe::1
        dnn: embb.testbed
        dev: ogstun
      
      metrics:
        server:
          - address: 127.0.0.7
            port: 9090
