apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      level: info
      file: /var/log/open5gs/upf.log
    
    upf:
      # PFCP interface (N4)
      pfcp:
        server:
          - address: 0.0.0.0
            port: 8805
      
      # GTP-U interface (N3)
      gtpu:
        server:
          - address: 0.0.0.0
            port: 2152
      
      # DNN configurations
      subnet:
        - dnn: embb.testbed
          addr: 10.45.0.1/24
          dev: ogstun
        
        - dnn: urllc.v2x
          addr: 10.45.1.1/24
          dev: ogstun2
        
        - dnn: mmtc.testbed
          addr: 10.45.2.1/24
          dev: ogstun3
      
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090