logger:
  file:
    path: /var/log/open5gs/upf.log
    timestamp: true
  default:
    timestamp: false
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

upf:
  pfcp:
    server:
      - address: 127.0.0.7
    client:
      smf:     #  UPF PFCP Client try to associate SMF PFCP Server
        - address: 127.0.0.4
  # Change GTP-U server address binding for external access
  gtpu:
    server:
      - address: 10.34.4.245
  session:
    - subnet: 10.45.0.0/24
      sst: 1
      # sd: 000001
      dnn: embb.testbed
      gateway: 10.45.0.1
      dev: ogstun
    - subnet: 10.45.1.0/24
      sst: 2
      # sd: 000002
      dnn: urllc.v2x
      gateway: 10.45.1.1
      dev: ogstun2
    - subnet: 10.45.2.0/24
      sst: 3
      # sd: 000003
      dnn: mmtc.testbed
      gateway: 10.45.2.1
      dev: ogstun3
    # - subnet: 2001:db8:cafe::/48
    #   gateway: 2001:db8:cafe::1
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090
