apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: open5gs
spec:
  type: NodePort
  selector:
    app: amf
  ports:
  - name: sbi
    port: 7777
    targetPort: 7777
    protocol: TCP
  - name: ngap
    port: 38412
    targetPort: 38412
    nodePort: 30412  # Valid NodePort range (30000-32767)
    protocol: SCTP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amf
  namespace: open5gs
spec:
  serviceName: amf
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: open5gs-amf:latest
        imagePullPolicy: Never
        ports:
        - name: sbi
          containerPort: 7777
          protocol: TCP
        - name: ngap
          containerPort: 38412
          protocol: SCTP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN  # Required for SCTP
        volumeMounts:
        - name: config
          mountPath: /etc/open5gs/custom
        - name: logs
          mountPath: /var/log/open5gs
          subPath: amf
      volumes:
      - name: config
        configMap:
          name: amf-config
      - name: logs
        hostPath:
          path: /mnt/data/open5gs-logs
          type: DirectoryOrCreate