# Service
---
apiVersion: v1
kind: Service
metadata:
  name: smf
  namespace: open5gs
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: smf
  ports:
  - name: sbi
    port: 7777
    targetPort: 7777
    protocol: TCP
  - name: pfcp
    port: 8805
    targetPort: 8805
    protocol: UDP
  - name: gtpc
    port: 2123
    targetPort: 2123
    protocol: UDP
  - name: gtpu
    port: 2152
    targetPort: 2152
    protocol: UDP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP


# StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smf
  namespace: open5gs
spec:
  serviceName: smf
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
        component: control-plane
    spec:
      initContainers:
      - name: wait-for-dependency
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Waiting for nrf..."
          until nc -z nrf.open5gs.svc.cluster.local 7777; do
            echo "nrf not ready, waiting..."
            sleep 2
          done

          echo "NRF ready. Proceeding to start SMF."
      containers:
      - name: smf
        image: open5gs-smf:latest
        imagePullPolicy: Never
        ports:
        - name: sbi
          containerPort: 7777
          protocol: TCP
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        - name: gtpc
          containerPort: 2123
          protocol: UDP
        - name: gtpu
          containerPort: 2152
          protocol: UDP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: DB_URI
          value: "mongodb://mongodb.open5gs.svc.cluster.local:27017/open5gs"
        volumeMounts:
        - name: config
          mountPath: /etc/open5gs/custom
        - name: logs
          mountPath: /var/log/open5gs
          subPath: smf
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["pgrep", "open5gs-smfd"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pgrep", "open5gs-smfd"]
          initialDelaySeconds: 5
          periodSeconds: 10
      
      volumes:
      - name: config
        configMap:
          name: smf-config
      - name: logs
        hostPath:
          path: /mnt/data/open5gs-logs
          type: DirectoryOrCreate
